languageCode = "en"
languageName = "English"
weight = 1
title = "Timothy Smith's Portfolio"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "Jan 2, 2006"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "Timothy Smith's Portfolio"
  # copyright = "Copy, _right?_ :thinking_face:"