name: MyWebsite CI/CD

on:
  push:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.112.0' # Specify the Hugo version you want to use

      - name: see hugo version
        run: hugo version
      
      - name: Verify Hugo Module Compatibility
        run: hugo mod graph

      - name: Build Hugo site
        run: hugo --theme=blowfish

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: public

      - name: Add nginx config to build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nginx
          path: nginx.conf

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    environment: STAGING
    runs-on: [self-hosted, portfolio.homelabtim.com, staging]
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Deploy site to NGINX
        run: |
          sudo rm -rf /var/www/*
          sudo cp -r * /var/www/

      - name: Configure NGINX
        run: |
          echo '
          server {
              listen 81;
              server_name ${{ secrets.DOMAIN }};
              root /var/www/html;
              index index.html;
              location / {
                  try_files $uri $uri/ =404;
              }
          }' | sudo tee /etc/nginx/sites-available/${{ secrets.DOMAIN }}

          sudo ln -sf /etc/nginx/sites-available/${{ secrets.DOMAIN }} /etc/nginx/sites-enabled/
          sudo systemctl reload nginx

  deploy-production:
    if: github.event.ref == 'refs/heads/main'
    environment: PRODUCTION
    runs-on: [self-hosted, portfolio.homelabtim.com, production]
    needs: build
    env:
      DOMAIN: ${{ vars.DOMAIN }}
      PORT: ${{ vars.PORT }}
    steps:
      - name: Cleanup build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Download NGINX config
        uses: actions/download-artifact@v3
        with:
          name: nginx

      - name: Set NGINX config
        run: |
          sed -i "s/{{DOMAIN}}/$DOMAIN/" nginx.conf
          sed -i "s/{{PORT}}/$PORT/" nginx.conf

          cat nginx.conf > /etc/nginx/sites-available/$DOMAIN

          if [ ! -L /etc/nginx/sites-enabled/$DOMAIN ] ; then
            ln -s /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/
          fi

      - name: Hot Reload NGINX
        run: /etc/init.d/nginx reload

      - name: Deploy to NGINX
        run: |
          rm -rf /var/www/$DOMAIN
          cp -r ./ /var/www/$DOMAIN